
from django.urls import path
from .views import *

urlpatterns = [
    path("admin-login/", admin_login_api, name="admin_login_api"),
    path("add-category/", add_category, name="add_category"),
    path("categories/", list_categories, name="list_categories"),
    path("foods/", list_foods, name="list_foods"),
    path("add-food-item/", add_food_item, name="add_food"),
    path("food_search/", food_search, name="food_search"),
    path("random_foods/", random_foods, name="random_foods"),
    path("register/", register_user, name="register_user"),
    path("login/", login_user, name="login_user"),
    path("foods/<int:id>/", food_detail, name="food_detail"),
    path("cart/add/", add_to_cart, name="add_to_cart"),
    path("cart/<int:user_id>/", add_cart_item, name="add_cart_item"),
    path("cart/update_quantity/", update_cart_quantity, name="update_cart_quantity"),
    path("cart/delete/<int:order_id>/", delete_cart_item, name="delete_cart_item"),
    path("place_order/", place_order, name="place_order"),
    path("orders/<int:user_id>/", user_orders, name="user_orders"),
    path("orders/by_order_number/<str:order_number>/", order_by_order_number, name="order_by_order_number"),
    path("order_address/<str:order_number>/", get_order_address, name="get_order_address"),
    path('invoice/<str:order_number>/', get_invoice, name="get_invoice"),
    path('user/<int:user_id>/', get_user_profile),
    path('user_update/<int:user_id>/', update_user_profile),
    path('change_password/<int:user_id>/', change_password),
    path('orders-not-confirmed/', orders_not_confirmed, name='orders_not_confirmed'),
    path('orders-confirmed/', orders_confirmed),
    path('food-being-prepared/', being_prepared),
    path('food-pickup/', food_pickup),
    path('orders-delivered/', food_delivered),
    path('order-cancelled/', order_cancelled),
    path('all-foods/', all_orders),
    path('order-between-dates/', order_between_dates),
    path('view-order-detail/<str:order_number>/', view_order_detail),
    path('update_order_status/', update_order_status),
    path('search-orders/', search_orders),
    path('category/<int:id>/', category_detail),
    path('delete-food/<int:id>/', delete_food),
    path('edit-food/<int:id>/', edit_food),
    path('users/', list_users),
    path('delete_user/<int:id>/', delete_user),
    path('edit-food/<int:id>/', edit_food),
    path('dashboard_metrics/', dashboard_metrics),
    path('monthly_sales_summary/', monthly_sales_summary, name='monthly_sales_summary'),
    path('top_selling_foods/', top_selling_foods, name='top_selling_foods'),
    path('weekly_sales_summary/', weekly_sales_summary, name='weekly_sales_summary'),
    path('weekly_user_registrations/', weekly_user_registrations, name='weekly_user_registrations'),
    path('track_order/<str:order_number>/', track_order, name='track_order'),
    path('cancel_order/<str:order_number>/', cancel_order, name='cancel_order'),
    path('reviews/add/<int:food_id>/', add_review),
    path('reviews/<int:food_id>/', food_reviews),
    path('review_edit/<int:id>/', review_detail),
    path('food_rating_summary/<int:food_id>/', food_rating_summary),
    path('all-reviews/', all_reviews),
    path('delete_review/<int:id>/', delete_review),
    path('orders-delivered/', food_delivered, name='food_delivered'),

    path('restaurants/', restaurant_list, name='restaurant_list'),
    path('restaurants/<int:id>/', restaurant_detail, name='restaurant_detail'),
    path('restaurants/<int:id>/suspend/', restaurant_suspend, name='restaurant_suspend'),
    path('restaurant-owner-login/', restaurant_owner_login, name='restaurant_owner_login'),
    path('delivered-orders/<int:user_id>/', delivered_orders_for_user, name='delivered_orders_for_user'),
    path('master-foods/', master_food_list),
    path('master-foods/<int:id>/', master_food_detail),

]