# Generated by Django 6.0.1 on 2026-03-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_image_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_name',
            new_name='food',
        ),
    ]
