# Generated by Django 6.0.1 on 2026-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foodtracking_orderaddress_paymentdetail_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_mode',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], max_length=20),
        ),
    ]
