# Generated by Django 6.0.1 on 2026-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_paymentdetail_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
