# Generated by Django 6.0.1 on 2026-03-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paymentdetail_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reg_gdate',
            new_name='reg_date',
        ),
    ]
