# Generated by Django 6.0.1 on 2026-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='FoodSys', max_length=100)),
                ('brand_logo_url', models.URLField(blank=True)),
                ('platform_currency', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('support_email', models.EmailField(default='support@foodsys.com', max_length=254)),
                ('support_phone', models.CharField(default='+1-800-FOODSYS', max_length=20)),
                ('platform_timezone', models.CharField(default='America/New_York', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('enable_restaurant_registration', models.BooleanField(default=True)),
                ('max_restaurants', models.IntegerField(default=500)),
            ],
        ),
    ]
