# Generated by Django 6.0.1 on 2026-03-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='master_foods/')),
                ('category', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='is_master_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='support_phone',
            field=models.CharField(default='+91-XXXXXXXXXX', max_length=20),
        ),
        migrations.CreateModel(
            name='RestaurantMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('prep_time', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.food')),
                ('master_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.masterfood')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'master_food')},
            },
        ),
    ]
