# Generated by Django 6.0.1 on 2026-03-23 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_masterfood_food_is_master_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.restaurant'),
        ),
    ]
