# Generated by Django 6.0.1 on 2026-03-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_orderaddress_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='item_description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
