# Generated by Django 6.0.1 on 2026-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_food_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
    ]
