# Generated by Django 6.0.1 on 2026-03-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_restaurant_is_discarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=525),
        ),
    ]
